In [2]:
import pandas as pd

In [4]:
import numpy as np

In [18]:
df = pd.DataFrame(np.arange(0,20).reshape(5, 4), index = ["Row 1", "Row 2", "Row 3", "Row 4", "Row 5"], columns = ["Column 1", "Column 2", "Column 3", "Column 4"])

In [6]:
print(df)

       Column 1  Column 2  Column 3  Column 4
Row 1         0         1         2         3
Row 2         4         5         6         7
Row 3         8         9        10        11
Row 4        12        13        14        15
Row 5        16        17        18        19

In [7]:
df.to_csv("Test.csv")

In [9]:
df.loc["Row 1"]

Column 1    0
Column 2    1
Column 3    2
Column 4    3
Name: Row 1, dtype: int64

In [10]:
type(df.loc["Row 1"])

pandas.Series

In [12]:
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []

In [13]:
df.iloc(:,:)

SyntaxError: invalid syntax (3206208381.py, line 1)

In [14]:
df.iloc[:,:]

Empty DataFrame
Columns: []
Index: []

In [15]:
df.loc["Column 1"]

KeyError: 'Column 1'

In [19]:
df.loc["Row 1", "Column 3"]

np.int64(2)

In [20]:
df

       Column 1  Column 2  Column 3  Column 4
Row 1         0         1         2         3
Row 2         4         5         6         7
Row 3         8         9        10        11
Row 4        12        13        14        15
Row 5        16        17        18        19

In [21]:
df.loc[:, :]

       Column 1  Column 2  Column 3  Column 4
Row 1         0         1         2         3
Row 2         4         5         6         7
Row 3         8         9        10        11
Row 4        12        13        14        15
Row 5        16        17        18        19

In [22]:
df.iloc[1, 4]

IndexError: index 4 is out of bounds for axis 0 with size 4

In [23]:
df.iloc[1, 3]

np.int64(7)

In [24]:
df.iloc[0:3, 0:2]

       Column 1  Column 2
Row 1         0         1
Row 2         4         5
Row 3         8         9

In [25]:
type(df.iloc[0:3, 0:2])

pandas.DataFrame

In [26]:
df.iloc[0:2, 0]

Row 1    0
Row 2    4
Name: Column 1, dtype: int64

In [27]:
type(df.iloc[0:2, 0])

pandas.Series

In [28]:
df.iloc[:,:].values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [29]:
df.iloc[:,:].shape

(5, 4)

In [30]:
df.isnull().sum()

Column 1    0
Column 2    0
Column 3    0
Column 4    0
dtype: int64

In [31]:
df["column 1"].value_counts()

KeyError: 'column 1'

In [32]:
df["Column 1"].value_counts

<bound method IndexOpsMixin.value_counts of Row 1     0
Row 2     4
Row 3     8
Row 4    12
Row 5    16
Name: Column 1, dtype: int64>

In [33]:
df["Row 1"].value_counts

KeyError: 'Row 1'

In [34]:
df["Column 3"]

Row 1     2
Row 2     6
Row 3    10
Row 4    14
Row 5    18
Name: Column 3, dtype: int64

In [35]:
df["Column 1", "Column 2"]

KeyError: ('Column 1', 'Column 2')

In [37]:
df[["Column 1", "Column 2", "Column 3"]]

       Column 1  Column 2  Column 3
Row 1         0         1         2
Row 2         4         5         6
Row 3         8         9        10
Row 4        12        13        14
Row 5        16        17        18

In [38]:
df.head()

       Column 1  Column 2  Column 3  Column 4
Row 1         0         1         2         3
Row 2         4         5         6         7
Row 3         8         9        10        11
Row 4        12        13        14        15
Row 5        16        17        18        19

In [40]:
df = pd.read_csv("test.csv")

In [41]:
df

  Unnamed: 0  Column 1  Column 2  Column 3  Column 4
0      Row 1         0         1         2         3
1      Row 2         4         5         6         7
2      Row 3         8         9        10        11
3      Row 4        12        13        14        15
4      Row 5        16        17        18        19

In [46]:
df = pd.read_csv("train.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'train.csv'

In [47]:
!pip install kaggle

Collecting kaggle
  Downloading kaggle-2.2.1-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: bleach in .\miniconda3\Lib\site-packages (from kaggle) (6.4.0)
Collecting jupytext (from kaggle)
  Downloading jupytext-1.19.3-py3-none-any.whl.metadata (15 kB)
Collecting kagglesdk<1.0,>=0.1.27 (from kaggle)
  Downloading kagglesdk-0.1.30-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: packaging in .\miniconda3\Lib\site-packages (from kaggle) (26.0)
Collecting protobuf (from kaggle)
  Downloading protobuf-7.35.1-cp310-abi3-win_amd64.whl.metadata (595 bytes)
Requirement already satisfied: python-dateutil in .\miniconda3\Lib\site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-dotenv in .\miniconda3\Lib\site-packages (from kaggle) (1.2.1)
Collecting python-slugify (from kaggle)
  Downloading python_slugify-8.0.4-py2.py3-none-any.whl.metadata (8.5 kB)
Requirement already satisfied: requests in .\miniconda3\Lib\site-packages (from kaggle) (2.33.1)
Requirement already satisfied: tqdm in .\miniconda3\Lib\site-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in .\miniconda3\Lib\site-packages (from kaggle) (2.6.3)
Requirement already satisfied: webencodings in .\miniconda3\Lib\site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: markdown-it-py>=1.0 in .\miniconda3\Lib\site-packages (from jupytext->kaggle) (4.0.0)
Collecting mdit-py-plugins (from jupytext->kaggle)
  Downloading mdit_py_plugins-0.6.1-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: nbformat in .\miniconda3\Lib\site-packages (from jupytext->kaggle) (5.10.4)
Requirement already satisfied: pyyaml in .\miniconda3\Lib\site-packages (from jupytext->kaggle) (6.0.3)
Requirement already satisfied: mdurl~=0.1 in .\miniconda3\Lib\site-packages (from markdown-it-py>=1.0->jupytext->kaggle) (0.1.2)
Requirement already satisfied: fastjsonschema>=2.15 in .\miniconda3\Lib\site-packages (from nbformat->jupytext->kaggle) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in .\miniconda3\Lib\site-packages (from nbformat->jupytext->kaggle) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in .\miniconda3\Lib\site-packages (from nbformat->jupytext->kaggle) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in .\miniconda3\Lib\site-packages (from nbformat->jupytext->kaggle) (5.15.1)
Requirement already satisfied: attrs>=22.2.0 in .\miniconda3\Lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in .\miniconda3\Lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in .\miniconda3\Lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in .\miniconda3\Lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2026.5.1)
Requirement already satisfied: platformdirs>=2.5 in .\miniconda3\Lib\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (4.9.4)
Requirement already satisfied: six>=1.5 in .\miniconda3\Lib\site-packages (from python-dateutil->kaggle) (1.17.0)
Collecting text-unidecode>=1.3 (from python-slugify->kaggle)
  Downloading text_unidecode-1.3-py2.py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in .\miniconda3\Lib\site-packages (from requests->kaggle) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in .\miniconda3\Lib\site-packages (from requests->kaggle) (3.11)
Requirement already satisfied: certifi>=2023.5.7 in .\miniconda3\Lib\site-packages (from requests->kaggle) (2026.5.20)
Requirement already satisfied: colorama in .\miniconda3\Lib\site-packages (from tqdm->kaggle) (0.4.6)
Downloading kaggle-2.2.1-py3-none-any.whl (132 kB)
Downloading kagglesdk-0.1.30-py3-none-any.whl (231 kB)
Downloading jupytext-1.19.3-py3-none-any.whl (170 kB)
Downloading mdit_py_plugins-0.6.1-py3-none-any.whl (66 kB)
Downloading protobuf-7.35.1-cp310-abi3-win_amd64.whl (439 kB)
Downloading python_slugify-8.0.4-py2.py3-none-any.whl (10 kB)
Downloading text_unidecode-1.3-py2.py3-none-any.whl (78 kB)
Installing collected packages: text-unidecode, python-slugify, protobuf, mdit-py-plugins, kagglesdk, jupytext, kaggle

   ----------- ---------------------------- 2/7 [protobuf]
   ----------- ---------------------------- 2/7 [protobuf]
   ----------- ---------------------------- 2/7 [protobuf]
   ----------- ---------------------------- 2/7 [protobuf]
   ----------- ---------------------------- 2/7 [protobuf]
   ----------- ---------------------------- 2/7 [protobuf]
   ----------------- ---------------------- 3/7 [mdit-py-plugins]
   ----------------- ---------------------- 3/7 [mdit-py-plugins]
   ---------------------- ----------------- 4/7 [kagglesdk]
   ---------------------- ----------------- 4/7 [kagglesdk]
   ---------------------- ----------------- 4/7 [kagglesdk]
   ---------------------- ----------------- 4/7 [kagglesdk]
   ---------------------- ----------------- 4/7 [kagglesdk]
   ---------------------- ----------------- 4/7 [kagglesdk]
   ---------------------- ----------------- 4/7 [kagglesdk]
   ---------------------- ----------------- 4/7 [kagglesdk]
   ---------------------- ----------------- 4/7 [kagglesdk]
   ---------------------- ----------------- 4/7 [kagglesdk]
   ---------------------- ----------------- 4/7 [kagglesdk]
   ---------------------- ----------------- 4/7 [kagglesdk]
   ---------------------- ----------------- 4/7 [kagglesdk]
   ---------------------------- ----------- 5/7 [jupytext]
   ---------------------------- ----------- 5/7 [jupytext]
   ---------------------------- ----------- 5/7 [jupytext]
   ---------------------------- ----------- 5/7 [jupytext]
   ---------------------------- ----------- 5/7 [jupytext]
   ---------------------------------- ----- 6/7 [kaggle]
   ---------------------------------- ----- 6/7 [kaggle]
   ---------------------------------------- 7/7 [kaggle]

Successfully installed jupytext-1.19.3 kaggle-2.2.1 kagglesdk-0.1.30 mdit-py-plugins-0.6.1 protobuf-7.35.1 python-slugify-8.0.4 text-unidecode-1.3

In [48]:
!mkdir ~/.kaggle

The syntax of the command is incorrect.

In [49]:
import kaggle

In [50]:
!kaggle datasets download yasserh/mercedesbenz-greener-manufacturing-dataset

Dataset URL: https://www.kaggle.com/datasets/yasserh/mercedesbenz-greener-manufacturing-dataset
License(s): CC0-1.0
Downloading mercedesbenz-greener-manufacturing-dataset.zip to C:\Users\HP

  0%|          | 0.00/564k [00:00<?, ?B/s]
100%|##########| 564k/564k [00:01<00:00, 505kB/s]
100%|##########| 564k/564k [00:01<00:00, 505kB/s]

In [51]:
import zipfile

with zipfile.ZipFile('mercedesbenz-greener-manufacturing-dataset.zip', 'r') as zip_ref:
    zip_ref.extractall()

In [52]:
import pandas as pd

df = pd.read_csv("train.csv")
df.head()

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
1,6,88.53,k,t,av,e,d,y,l,o,...,1,0,0,0,0,0,0,0,0,0
2,7,76.26,az,w,n,c,d,x,j,x,...,0,0,0,0,0,0,1,0,0,0
3,9,80.62,az,t,n,f,d,x,l,e,...,0,0,0,0,0,0,0,0,0,0
4,13,78.02,az,v,n,f,d,h,d,n,...,0,0,0,0,0,0,0,0,0,0

In [53]:
import os
os.listdir()

['.anaconda',
 '.android',
 '.antigravity-ide',
 '.bashrc',
 '.bash_history',
 '.bash_profile',
 '.cache',
 '.conda',
 '.config',
 '.deepface',
 '.gemini',
 '.gitconfig',
 '.gitignore',
 '.gradle',
 '.idlerc',
 '.ipynb_checkpoints',
 '.ipython',
 '.jdks',
 '.jupyter',
 '.kaggle',
 '.keras',
 '.lesshst',
 '.local',
 '.matplotlib',
 '.node_repl_history',
 '.openshot_qt',
 '.streamlit',
 '.th-client',
 '.TurboVPN',
 '.viminfo',
 '.VirtualBox',
 '.vscode',
 'apnaCollege',
 'AppData',
 'Application Data',
 'AR ID CARD',
 'Contacts',
 'Cookies',
 'DishaVerma',
 'Documents',
 'Downloads',
 'Favorites',
 'HTML',
 'IdeaProjects',
 'Links',
 'Local Settings',
 'mercedesbenz-greener-manufacturing-dataset.zip',
 'miniconda3',
 'Music',
 'My Documents',
 'My project',
 'NetHood',
 'New folder',
 'node_modules',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{2ad838bc-efea-11ee-a54d-000d3a94eaa1}.TM.blf',
 'NTUSER.DAT{2ad838bc-efea-11ee-a54d-000d3a94eaa1}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{2ad838bc-efea-11ee-a54d-000d3a94eaa1}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'OneDrive',
 'package-lock.json',
 'package.json',
 'pandas.ipynb',
 'PrintHood',
 'PycharmProjects',
 'Recent',
 'Saved Games',
 'Searches',
 'SendTo',
 'source',
 'Start Menu',
 'Templates',
 'Test.csv',
 'train.csv',
 'upto_NumPy.ipynb',
 'Vermss',
 'Videos']

In [54]:
df.head()

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
1,6,88.53,k,t,av,e,d,y,l,o,...,1,0,0,0,0,0,0,0,0,0
2,7,76.26,az,w,n,c,d,x,j,x,...,0,0,0,0,0,0,1,0,0,0
3,9,80.62,az,t,n,f,d,x,l,e,...,0,0,0,0,0,0,0,0,0,0
4,13,78.02,az,v,n,f,d,h,d,n,...,0,0,0,0,0,0,0,0,0,0

In [55]:
df.info

<bound method DataFrame.info of         ID       y  X0 X1  X2 X3 X4  X5 X6 X8  ...  X375  X376  X377  X378  \
0        0  130.81   k  v  at  a  d   u  j  o  ...     0     0     1     0
1        6   88.53   k  t  av  e  d   y  l  o  ...     1     0     0     0
2        7   76.26  az  w   n  c  d   x  j  x  ...     0     0     0     0
3        9   80.62  az  t   n  f  d   x  l  e  ...     0     0     0     0
4       13   78.02  az  v   n  f  d   h  d  n  ...     0     0     0     0
...    ...     ...  .. ..  .. .. ..  .. .. ..  ...   ...   ...   ...   ...
4204  8405  107.39  ak  s  as  c  d  aa  d  q  ...     1     0     0     0
4205  8406  108.77   j  o   t  d  d  aa  h  h  ...     0     1     0     0
4206  8412  109.22  ak  v   r  a  d  aa  g  e  ...     0     0     1     0
4207  8415   87.48  al  r   e  f  d  aa  l  u  ...     0     0     0     0
4208  8417  110.85   z  r  ae  c  d  aa  g  w  ...     1     0     0     0

      X379  X380  X382  X383  X384  X385
0        0     0     0     0     0     0
1        0     0     0     0     0     0
2        0     0     1     0     0     0
3        0     0     0     0     0     0
4        0     0     0     0     0     0
...    ...   ...   ...   ...   ...   ...
4204     0     0     0     0     0     0
4205     0     0     0     0     0     0
4206     0     0     0     0     0     0
4207     0     0     0     0     0     0
4208     0     0     0     0     0     0

[4209 rows x 378 columns]>

In [56]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), str(8)
memory usage: 12.1 MB

In [57]:
df.describe()

,ID,y,X10,X11,X12,X13,X14,X15,X16,X17,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
count,4209.000000,4209.000000,4209.000000,4209.0,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,...,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000
mean,4205.960798,100.669318,0.013305,0.0,0.075077,0.057971,0.428130,0.000475,0.002613,0.007603,...,0.318841,0.057258,0.314802,0.020670,0.009503,0.008078,0.007603,0.001663,0.000475,0.001426
std,2437.608688,12.679381,0.114590,0.0,0.263547,0.233716,0.494867,0.021796,0.051061,0.086872,...,0.466082,0.232363,0.464492,0.142294,0.097033,0.089524,0.086872,0.040752,0.021796,0.037734
min,0.000000,72.110000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2095.000000,90.820000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,4220.000000,99.150000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,6314.000000,109.010000,0.000000,0.0,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,...,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,8417.000000,265.320000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [58]:
df['X0'].value_counts()

X0
z     360
ak    349
y     324
ay    313
t     306
x     300
o     269
f     227
n     195
w     182
j     181
az    175
aj    151
s     106
ap    103
h      75
d      73
al     67
v      36
af     35
ai     34
m      34
e      32
ba     27
at     25
a      21
ax     19
am     18
aq     18
i      18
u      17
l      16
aw     16
ad     14
k      11
b      11
au     11
as     10
r      10
bc      6
ao      4
c       3
q       2
aa      2
ac      1
g       1
ab      1
Name: count, dtype: int64

In [59]:
df['x0'].value_counts()

KeyError: 'x0'

In [60]:
df['X0'].unique()

<StringArray>
[ 'k', 'az',  't', 'al',  'o',  'w',  'j',  'h',  's',  'n', 'ay',  'f',  'x',
  'y', 'aj', 'ak', 'am',  'z',  'q', 'at', 'ap',  'v', 'af',  'a',  'e', 'ai',
  'd', 'aq',  'c', 'aa', 'ba', 'as',  'i',  'r',  'b', 'ax', 'bc',  'u', 'ad',
 'au',  'm',  'l', 'aw', 'ao', 'ac',  'g', 'ab']
Length: 47, dtype: str

In [61]:
df[df['y']>100]

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
6,24,128.76,al,r,e,f,d,f,h,s,...,0,0,0,0,0,0,0,0,0,0
8,27,108.67,w,s,as,e,d,f,i,h,...,1,0,0,0,0,0,0,0,0,0
9,30,126.99,j,b,aq,c,d,f,a,e,...,0,0,1,0,0,0,0,0,0,0
10,31,102.09,h,r,r,f,d,f,h,p,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4202,8402,123.34,ap,l,s,c,d,aa,d,r,...,0,0,0,0,0,0,0,0,0,0
4204,8405,107.39,ak,s,as,c,d,aa,d,q,...,1,0,0,0,0,0,0,0,0,0
4205,8406,108.77,j,o,t,d,d,aa,h,h,...,0,1,0,0,0,0,0,0,0,0
4206,8412,109.22,ak,v,r,a,d,aa,g,e,...,0,0,1,0,0,0,0,0,0,0
4208,8417,110.85,z,r,ae,c,d,aa,g,w,...,1,0,0,0,0,0,0,0,0,0

In [62]:
df[df['y']>1000]

Empty DataFrame
Columns: [ID, y, X0, X1, X2, X3, X4, X5, X6, X8, X10, X11, X12, X13, X14, X15, X16, X17, X18, X19, X20, X21, X22, X23, X24, X26, X27, X28, X29, X30, X31, X32, X33, X34, X35, X36, X37, X38, X39, X40, X41, X42, X43, X44, X45, X46, X47, X48, X49, X50, X51, X52, X53, X54, X55, X56, X57, X58, X59, X60, X61, X62, X63, X64, X65, X66, X67, X68, X69, X70, X71, X73, X74, X75, X76, X77, X78, X79, X80, X81, X82, X83, X84, X85, X86, X87, X88, X89, X90, X91, X92, X93, X94, X95, X96, X97, X98, X99, X100, X101, ...]
Index: []

[0 rows x 378 columns]

In [63]:
from io import StringIO, BytesIO

In [64]:
data = ('col1, col2, col3\n')

In [72]:
data = ('col1,col2,col3\n'
       'x, y, 1\n'
       'a, b, 2\n'
       'c, d, 3')

In [73]:
type(data)

str

In [74]:
pd.read_csv(StringIO(data))

  col1 col2  col3
0    x    y     1
1    a    b     2
2    c    d     3

In [75]:
df = pd.read_csv(StringIO(data), usecols = ['col1', 'col3'])

In [76]:
df

  col1  col3
0    x     1
1    a     2
2    c     3

In [77]:
df.to_csv("Test.csv")

In [78]:
df

  col1  col3
0    x     1
1    a     2
2    c     3

In [79]:
data = ('a,b,c,d\n'
       '1,2,3,4\n'
       '5,6,7,8\n'
       '9,10,11')

In [80]:
print(data)

a,b,c,d
1,2,3,4
5,6,7,8
9,10,11

In [83]:
df = pd.read_csv(StringIO(data), dtype =float)

In [84]:
df

     a     b     c    d
0  1.0   2.0   3.0  4.0
1  5.0   6.0   7.0  8.0
2  9.0  10.0  11.0  NaN

In [85]:
df['a']

0    1.0
1    5.0
2    9.0
Name: a, dtype: float64

In [86]:
df.dtypes

a    float64
b    float64
c    float64
d    float64
dtype: object

In [87]:
pd.read_csv(StringIO(data), index_col = 2)

    a   b    d
c
3   1   2  4.0
7   5   6  8.0
11  9  10  NaN

In [107]:
data = ('a,b,c\n'
       '4,apple,bat\n'
       '8,orange,cow')

In [108]:
df = pd.read_csv(StringIO(data))

In [109]:
df

   a       b    c
0  4   apple  bat
1  8  orange  cow

In [110]:
df = pd.read_csv(StringIO(data))

In [111]:
df

   a       b    c
0  4   apple  bat
1  8  orange  cow

In [121]:
data = 'a,b\n "Hello my name is \\"Bob\\" I am 5 years old", 5'

In [122]:
data

'a,b\n "Hello my name is \\"Bob\\" I am 5 years old", 5'

In [123]:
pd.read_csv(StringIO(data), escapechar = '\\')

                                            a  b
0   "Hello my name is "Bob" I am 5 years old"  5

In [124]:
git status

SyntaxError: invalid syntax (339777499.py, line 1)

In [125]:
git init

SyntaxError: invalid syntax (2830201818.py, line 1)

In [126]:
import git

ModuleNotFoundError: No module named 'git'

In [127]:
!git status

fatal: not a git repository (or any of the parent directories): .git

In [128]:
!git init

Initialized empty Git repository in C:/Users/HP/.git/

In [129]:
!git status

On branch master

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.TurboVPN/
	.VirtualBox/
	.anaconda/
	.android/
	.antigravity-ide/
	.bash_history
	.bash_profile
	.bashrc
	.cache/
	.conda/
	.config/
	.deepface/
	.gemini/
	.gitconfig
	.gitignore
	.idlerc/
	.ipynb_checkpoints/
	.ipython/
	.jdks/
	.jupyter/
	.kaggle/
	.keras/
	.lesshst
	.local/
	.matplotlib/
	.node_repl_history
	.streamlit/
	.th-client/
	.viminfo
	AR ID CARD/
	AppData/
	Contacts/
	DishaVerma/
	Downloads/
	Favorites/
	IdeaProjects/
	Links/
	Music/
	My project/
	NTUSER.DAT
	NTUSER.DAT{2ad838bc-efea-11ee-a54d-000d3a94eaa1}.TM.blf
	NTUSER.DAT{2ad838bc-efea-11ee-a54d-000d3a94eaa1}.TMContainer00000000000000000001.regtrans-ms
	NTUSER.DAT{2ad838bc-efea-11ee-a54d-000d3a94eaa1}.TMContainer00000000000000000002.regtrans-ms
	OneDrive/
	PycharmProjects/
	Saved Games/
	Searches/
	Test.csv
	Vermss/
	Videos/
	apnaCollege/
	mercedesbenz-greener-manufacturing-dataset.zip
	miniconda3/
	node_modules/
	ntuser.dat.LOG1
	ntuser.dat.LOG2
	ntuser.ini
	package-lock.json
	package.json
	pandas.ipynb
	train.csv
	upto_NumPy.ipynb

nothing added to commit but untracked files present (use "git add" to track)

warning: could not open directory 'Application Data/': Permission denied
warning: could not open directory 'Cookies/': Permission denied
warning: could not open directory 'Documents/My Music/': Permission denied
warning: could not open directory 'Documents/My Pictures/': Permission denied
warning: could not open directory 'Documents/My Videos/': Permission denied
warning: could not open directory 'Local Settings/': Permission denied
warning: could not open directory 'My Documents/': Permission denied
warning: could not open directory 'NetHood/': Permission denied
warning: could not open directory 'PrintHood/': Permission denied
warning: could not open directory 'Recent/': Permission denied
warning: could not open directory 'SendTo/': Permission denied
warning: could not open directory 'Start Menu/': Permission denied
warning: could not open directory 'Templates/': Permission denied

In [130]:
df = pd.DataFrame()

In [131]:
print(df)

Empty DataFrame
Columns: []
Index: []

In [132]:
!git status

On branch master

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.TurboVPN/
	.VirtualBox/
	.anaconda/
	.android/
	.antigravity-ide/
	.bash_history
	.bash_profile
	.bashrc
	.cache/
	.conda/
	.config/
	.deepface/
	.gemini/
	.gitconfig
	.gitignore
	.idlerc/
	.ipynb_checkpoints/
	.ipython/
	.jdks/
	.jupyter/
	.kaggle/
	.keras/
	.lesshst
	.local/
	.matplotlib/
	.node_repl_history
	.streamlit/
	.th-client/
	.viminfo
	AR ID CARD/
	AppData/
	Contacts/
	DishaVerma/
	Downloads/
	Favorites/
	IdeaProjects/
	Links/
	Music/
	My project/
	NTUSER.DAT
	NTUSER.DAT{2ad838bc-efea-11ee-a54d-000d3a94eaa1}.TM.blf
	NTUSER.DAT{2ad838bc-efea-11ee-a54d-000d3a94eaa1}.TMContainer00000000000000000001.regtrans-ms
	NTUSER.DAT{2ad838bc-efea-11ee-a54d-000d3a94eaa1}.TMContainer00000000000000000002.regtrans-ms
	OneDrive/
	PycharmProjects/
	Saved Games/
	Searches/
	Test.csv
	Vermss/
	Videos/
	apnaCollege/
	mercedesbenz-greener-manufacturing-dataset.zip
	miniconda3/
	node_modules/
	ntuser.dat.LOG1
	ntuser.dat.LOG2
	ntuser.ini
	package-lock.json
	package.json
	pandas.ipynb
	train.csv
	upto_NumPy.ipynb

nothing added to commit but untracked files present (use "git add" to track)

warning: could not open directory 'Application Data/': Permission denied
warning: could not open directory 'Cookies/': Permission denied
warning: could not open directory 'Documents/My Music/': Permission denied
warning: could not open directory 'Documents/My Pictures/': Permission denied
warning: could not open directory 'Documents/My Videos/': Permission denied
warning: could not open directory 'Local Settings/': Permission denied
warning: could not open directory 'My Documents/': Permission denied
warning: could not open directory 'NetHood/': Permission denied
warning: could not open directory 'PrintHood/': Permission denied
warning: could not open directory 'Recent/': Permission denied
warning: could not open directory 'SendTo/': Permission denied
warning: could not open directory 'Start Menu/': Permission denied
warning: could not open directory 'Templates/': Permission denied

In [133]:
import os
print(os.getcwd())

C:\Users\HP

In [134]:
!git remote -v

In [135]:
import os
print(os.path.abspath("pandas.ipynb"))

C:\Users\HP\pandas.ipynb

In [1]:
!git status

On branch main
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.TurboVPN/
	.VirtualBox/
	.anaconda/
	.android/
	.antigravity-ide/
	.bash_history
	.bash_profile
	.bashrc
	.cache/
	.conda/
	.config/
	.deepface/
	.gemini/
	.gitconfig
	.gitignore
	.idlerc/
	.ipynb_checkpoints/
	.ipython/
	.jdks/
	.jupyter/
	.kaggle/
	.keras/
	.lesshst
	.local/
	.matplotlib/
	.node_repl_history
	.streamlit/
	.th-client/
	.viminfo
	AR ID CARD/
	AppData/
	Contacts/
	DishaVerma/
	Downloads/
	Favorites/
	IdeaProjects/
	Links/
	Music/
	My project/
	NTUSER.DAT
	NTUSER.DAT{2ad838bc-efea-11ee-a54d-000d3a94eaa1}.TM.blf
	NTUSER.DAT{2ad838bc-efea-11ee-a54d-000d3a94eaa1}.TMContainer00000000000000000001.regtrans-ms
	NTUSER.DAT{2ad838bc-efea-11ee-a54d-000d3a94eaa1}.TMContainer00000000000000000002.regtrans-ms
	OneDrive/
	PycharmProjects/
	Python/
	Saved Games/
	Searches/
	Test.csv
	Vermss/
	Videos/
	apnaCollege/
	mercedesbenz-greener-manufacturing-dataset.zip
	miniconda3/
	node_modules/
	ntuser.dat.LOG1
	ntuser.dat.LOG2
	ntuser.ini
	package-lock.json
	package.json
	train.csv
	upto_NumPy.ipynb

nothing added to commit but untracked files present (use "git add" to track)

warning: could not open directory 'Application Data/': Permission denied
warning: could not open directory 'Cookies/': Permission denied
warning: could not open directory 'Documents/My Music/': Permission denied
warning: could not open directory 'Documents/My Pictures/': Permission denied
warning: could not open directory 'Documents/My Videos/': Permission denied
warning: could not open directory 'Local Settings/': Permission denied
warning: could not open directory 'My Documents/': Permission denied
warning: could not open directory 'NetHood/': Permission denied
warning: could not open directory 'PrintHood/': Permission denied
warning: could not open directory 'Recent/': Permission denied
warning: could not open directory 'SendTo/': Permission denied
warning: could not open directory 'Start Menu/': Permission denied
warning: could not open directory 'Templates/': Permission denied

# Reading JSON content

In [8]:
data = '{"employee_name" : "Disha Verma", "e-mail": "ms.dishaverma.20@gmail.com", "job_profile": [{"title1":"Team Lead", "title2":"Sr. Developer"}]}'
pd.read_json(data)

FileNotFoundError: File {"employee_name" : "Disha Verma", "e-mail": "ms.dishaverma.20@gmail.com", "job_profile": [{"title1":"Team Lead", "title2":"Sr. Developer"}]} does not exist

In [3]:
pd.read_json(data)

NameError: name 'pd' is not defined

In [4]:
import pandas as pd

In [5]:
pd.read_json(data)

FileNotFoundError: File {"employee_name" = "Disha Verma", "e-mail": "ms.dishaverma.20@gmail.com", "job_profile": [{"title1":"Team Lead", "title2":"Sr. Developer"}]} does not exist

In [9]:
data = '{"employee_name" : "Disha Verma", "e-mail": "ms.dishaverma.20@gmail.com", "job_profile": [{"title1":"Team Lead", "title2":"Sr. Developer"}]}'
pd.read_json(data)

FileNotFoundError: File {"employee_name" : "Disha Verma", "e-mail": "ms.dishaverma.20@gmail.com", "job_profile": [{"title1":"Team Lead", "title2":"Sr. Developer"}]} does not exist

In [45]:
from io import StringIO
data = ['{"employee_name" : "Disha Verma", "e-mail": "ms.dishaverma.20@gmail.com", "job_profile": [{"title1":"Team Lead", "title2":"Sr. Developer"}]}','{"employee_name" : "Disha Verma", "e-mail": "ms.dishaverma.20@gmail.com", "job_profile": [{"title1":"Team Lead", "title2":"Sr. Developer"}]}']
json_string = '[' + ','.join(data) + ']'
df1 = pd.read_json(StringIO(json_string))
# pd.read_json(data)
# df.read_json() # wrong ho jayga issey

In [46]:
type(data)
type(df1)

pandas.DataFrame

In [11]:
# as a DataFrame

In [12]:
data = '''[{"employee_name" : "Disha Verma", "e-mail": "ms.dishaverma.20@gmail.com", "job_profile": [{"title1":"Team Lead", "title2":"Sr. Developer"}]}]'''

In [13]:
df

NameError: name 'df' is not defined

In [24]:
df = pd.read_json(StringIO(data))

In [25]:
df

,employee_name,e-mail,job_profile
0,Disha Verma,ms.dishaverma.20@gmail.com,"{'title1': 'Team Lead', 'title2': 'Sr. Develop..."

In [23]:
pd.to_csv(df)

AttributeError: module 'pandas' has no attribute 'to_csv'

In [22]:
df.to_csv()

',employee_name,e-mail,job_profile\r\n0,Disha Verma,ms.dishaverma.20@gmail.com,"[{\'title1\': \'Team Lead\', \'title2\': \'Sr. Developer\'}]"\r\n'

In [18]:
!git status

On branch main
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   pandas.ipynb

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.TurboVPN/
	.VirtualBox/
	.anaconda/
	.android/
	.antigravity-ide/
	.bash_history
	.bash_profile
	.bashrc
	.cache/
	.conda/
	.config/
	.deepface/
	.gemini/
	.gitconfig
	.gitignore
	.idlerc/
	.ipynb_checkpoints/
	.ipython/
	.jdks/
	.jupyter/
	.kaggle/
	.keras/
	.lesshst
	.local/
	.matplotlib/
	.node_repl_history
	.streamlit/
	.th-client/
	.viminfo
	AR ID CARD/
	AppData/
	Contacts/
	DishaVerma/
	Downloads/
	Favorites/
	IdeaProjects/
	Links/
	Music/
	My project/
	NTUSER.DAT
	NTUSER.DAT{2ad838bc-efea-11ee-a54d-000d3a94eaa1}.TM.blf
	NTUSER.DAT{2ad838bc-efea-11ee-a54d-000d3a94eaa1}.TMContainer00000000000000000001.regtrans-ms
	NTUSER.DAT{2ad838bc-efea-11ee-a54d-000d3a94eaa1}.TMContainer00000000000000000002.regtrans-ms
	OneDrive/
	PycharmProjects/
	Python/
	Saved Games/
	Searches/
	Test.csv
	Vermss/
	Videos/
	apnaCollege/
	mercedesbenz-greener-manufacturing-dataset.zip
	miniconda3/
	node_modules/
	ntuser.dat.LOG1
	ntuser.dat.LOG2
	ntuser.ini
	package-lock.json
	package.json
	train.csv
	upto_NumPy.ipynb

no changes added to commit (use "git add" and/or "git commit -a")

warning: could not open directory 'Application Data/': Permission denied
warning: could not open directory 'Cookies/': Permission denied
warning: could not open directory 'Documents/My Music/': Permission denied
warning: could not open directory 'Documents/My Pictures/': Permission denied
warning: could not open directory 'Documents/My Videos/': Permission denied
warning: could not open directory 'Local Settings/': Permission denied
warning: could not open directory 'My Documents/': Permission denied
warning: could not open directory 'NetHood/': Permission denied
warning: could not open directory 'PrintHood/': Permission denied
warning: could not open directory 'Recent/': Permission denied
warning: could not open directory 'SendTo/': Permission denied
warning: could not open directory 'Start Menu/': Permission denied
warning: could not open directory 'Templates/': Permission denied

In [26]:
df.to_json()

'{"employee_name":{"0":"Disha Verma"},"e-mail":{"0":"ms.dishaverma.20@gmail.com"},"job_profile":{"0":{"title1":"Team Lead","title2":"Sr. Developer"}}}'

In [27]:
df.to_json(orient = "records")

'[{"employee_name":"Disha Verma","e-mail":"ms.dishaverma.20@gmail.com","job_profile":{"title1":"Team Lead","title2":"Sr. Developer"}}]'

# Reading HTML content

In [47]:
url = 'https://www.fdic.gov/bank-failures/failed-bank-list'
df = pd.read_html(url)

ImportError: `Import lxml` failed.  Use pip or conda to install the lxml package.

In [48]:
!pip install lxml

Collecting lxml
  Downloading lxml-6.1.1-cp313-cp313-win_amd64.whl.metadata (3.6 kB)
Downloading lxml-6.1.1-cp313-cp313-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   -------------------- ------------------- 2.1/4.0 MB 13.2 MB/s eta 0:00:01
   ------------------------------------ --- 3.7/4.0 MB 9.4 MB/s eta 0:00:01
   ---------------------------------------- 4.0/4.0 MB 9.1 MB/s  0:00:00
Installing collected packages: lxml
Successfully installed lxml-6.1.1

In [49]:
url = 'https://www.fdic.gov/bank-failures/failed-bank-list'
df = pd.read_html(url)

In [50]:
df[0]

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Community Bank and Trust - West Georgia,LaGrange,Georgia,25796,Anchor Bank,"May 1, 2026",10551
1,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550
2,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
3,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
4,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
5,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
6,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
7,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
8,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
9,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
10,Silicon Valley Bank,Santa Clara,California,24735,First–Citizens Bank & Trust Company,"March 10, 2023",10539
11,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
12,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
13,The First State Bank,Barboursville,West Virginia,14361,"MVB Bank, Inc.","April 3, 2020",10536
14,Ericson State Bank,Ericson,Nebraska,18265,Farmers and Merchants Bank,"February 14, 2020",10535
15,City National Bank of New Jersey,Newark,New Jersey,21111,Industrial Bank,"November 1, 2019",10534
16,Resolute Bank,Maumee,Ohio,58317,Buckeye State Bank,"October 25, 2019",10533
17,Louisa Community Bank,Louisa,Kentucky,58112,Kentucky Farmers Bank Corporation,"October 25, 2019",10532
18,The Enloe State Bank,Cooper,Texas,10716,"Legend Bank, N. A.","May 31, 2019",10531
19,Washington Federal Bank for Savings,Chicago,Illinois,30570,Royal Savings Bank,"December 15, 2017",10530
20,The Farmers and Merchants State Bank of Argonia,Argonia,Kansas,17719,Conway Bank,"October 13, 2017",10529
21,Fayette County Bank,Saint Elmo,Illinois,1802,"United Fidelity Bank, fsb","May 26, 2017",10528
22,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,Wisconsin,30003,First-Citizens Bank & Trust Company,"May 5, 2017",10527
23,First NBC Bank,New Orleans,Louisiana,58302,Whitney Bank,"April 28, 2017",10526
24,Proficio Bank,Cottonwood Heights,Utah,35495,Cache Valley Bank,"March 3, 2017",10525

In [51]:
df[1]

IndexError: list index out of range

In [53]:
url2 = 'https://en.wikipedia.org/wiki/Mobile_country_code'
pd.read_html(url2)

HTTPError: HTTP Error 403: Forbidden

# Reading Excel Files

In [58]:
df = pd.read_excel(r"C:\Users\HP\Downloads\Desktop\Papa's Doc\Holi Chanda.xlsx")

ImportError: `Import openpyxl` failed.  Use pip or conda to install the openpyxl package.

In [59]:
!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

In [60]:
df = pd.read_excel(r"C:\Users\HP\Downloads\Desktop\Papa's Doc\Holi Chanda.xlsx")

In [61]:
df

,Shree Rajesh Pradhan (Lallu),Vansh Market,2024-03-19 00:00:00,2100
0,Shree Rajjo Verma,Ganga Market,2024-03-19,500.0
1,Shree Ashok Verma (Pappu),Papad vali gali,2024-03-19,500.0
2,Shree Dinesh Verma,Papad vali gali,2024-03-19,1100.0
3,Shree Anuj Soni (Balai),Shubash Market,2024-03-19,251.0
4,Shree Shekhar Verma (Lovly),Shubash Market,2024-03-19,1100.0
...,...,...,...,...
1048570,NaN,NaN,NaT,NaN
1048571,NaN,NaN,NaT,NaN
1048572,NaN,NaN,NaT,NaN
1048573,NaN,NaN,NaT,NaN
1048574,NaN,NaN,NaT,88005.0

In [62]:
df.head()

  Shree Rajesh Pradhan (Lallu)     Vansh Market 2024-03-19 00:00:00    2100
0            Shree Rajjo Verma     Ganga Market          2024-03-19   500.0
1    Shree Ashok Verma (Pappu)  Papad vali gali          2024-03-19   500.0
2           Shree Dinesh Verma  Papad vali gali          2024-03-19  1100.0
3      Shree Anuj Soni (Balai)   Shubash Market          2024-03-19   251.0
4  Shree Shekhar Verma (Lovly)   Shubash Market          2024-03-19  1100.0

# Pickling

In [66]:
df.to_pickle('df')

In [67]:
dfs = pd.read_pickle('df')

In [68]:
dfs

,Shree Rajesh Pradhan (Lallu),Vansh Market,2024-03-19 00:00:00,2100
0,Shree Rajjo Verma,Ganga Market,2024-03-19,500.0
1,Shree Ashok Verma (Pappu),Papad vali gali,2024-03-19,500.0
2,Shree Dinesh Verma,Papad vali gali,2024-03-19,1100.0
3,Shree Anuj Soni (Balai),Shubash Market,2024-03-19,251.0
4,Shree Shekhar Verma (Lovly),Shubash Market,2024-03-19,1100.0
...,...,...,...,...
1048570,NaN,NaN,NaT,NaN
1048571,NaN,NaN,NaT,NaN
1048572,NaN,NaN,NaT,NaN
1048573,NaN,NaN,NaT,NaN
1048574,NaN,NaN,NaT,88005.0

In [69]:
dfs.head()

  Shree Rajesh Pradhan (Lallu)     Vansh Market 2024-03-19 00:00:00    2100
0            Shree Rajjo Verma     Ganga Market          2024-03-19   500.0
1    Shree Ashok Verma (Pappu)  Papad vali gali          2024-03-19   500.0
2           Shree Dinesh Verma  Papad vali gali          2024-03-19  1100.0
3      Shree Anuj Soni (Balai)   Shubash Market          2024-03-19   251.0
4  Shree Shekhar Verma (Lovly)   Shubash Market          2024-03-19  1100.0

In [70]:
!git status

On branch main
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   pandas.ipynb

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.TurboVPN/
	.VirtualBox/
	.anaconda/
	.android/
	.antigravity-ide/
	.bash_history
	.bash_profile
	.bashrc
	.cache/
	.conda/
	.config/
	.deepface/
	.gemini/
	.gitconfig
	.gitignore
	.idlerc/
	.ipynb_checkpoints/
	.ipython/
	.jdks/
	.jupyter/
	.kaggle/
	.keras/
	.lesshst
	.local/
	.matplotlib/
	.node_repl_history
	.streamlit/
	.th-client/
	.viminfo
	AR ID CARD/
	AppData/
	Contacts/
	DishaVerma/
	Downloads/
	Favorites/
	IdeaProjects/
	Links/
	Music/
	My project/
	NTUSER.DAT
	NTUSER.DAT{2ad838bc-efea-11ee-a54d-000d3a94eaa1}.TM.blf
	NTUSER.DAT{2ad838bc-efea-11ee-a54d-000d3a94eaa1}.TMContainer00000000000000000001.regtrans-ms
	NTUSER.DAT{2ad838bc-efea-11ee-a54d-000d3a94eaa1}.TMContainer00000000000000000002.regtrans-ms
	OneDrive/
	PycharmProjects/
	Python/
	Saved Games/
	Searches/
	Test.csv
	Vermss/
	Videos/
	apnaCollege/
	df
	mercedesbenz-greener-manufacturing-dataset.zip
	miniconda3/
	node_modules/
	ntuser.dat.LOG1
	ntuser.dat.LOG2
	ntuser.ini
	package-lock.json
	package.json
	train.csv
	upto_NumPy.ipynb

no changes added to commit (use "git add" and/or "git commit -a")

warning: could not open directory 'Application Data/': Permission denied
warning: could not open directory 'Cookies/': Permission denied
warning: could not open directory 'Documents/My Music/': Permission denied
warning: could not open directory 'Documents/My Pictures/': Permission denied
warning: could not open directory 'Documents/My Videos/': Permission denied
warning: could not open directory 'Local Settings/': Permission denied
warning: could not open directory 'My Documents/': Permission denied
warning: could not open directory 'NetHood/': Permission denied
warning: could not open directory 'PrintHood/': Permission denied
warning: could not open directory 'Recent/': Permission denied
warning: could not open directory 'SendTo/': Permission denied
warning: could not open directory 'Start Menu/': Permission denied
warning: could not open directory 'Templates/': Permission denied

In [71]:
!git add pandas.ipynb

warning: in the working copy of 'pandas.ipynb', LF will be replaced by CRLF the next time Git touches it

In [72]:
!git commit -m "Pandas completed"

[main 313e78b] Pandas completed
 1 file changed, 1709 insertions(+), 2 deletions(-)

In [73]:
!git push

fatal: The upstream branch of your current branch does not match
the name of your current branch.  To push to the upstream branch
on the remote, use

    git push origin HEAD:master

To push to the branch of the same name on the remote, use

    git push origin HEAD

To choose either option permanently, see push.default in 'git help config'.

To avoid automatically configuring an upstream branch when its name
won't match the local branch, see option 'simple' of branch.autoSetupMerge
in 'git help config'.

In [74]:
!git push -u origin main

To https://github.com/DishaVerma-20/Python.git
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'https://github.com/DishaVerma-20/Python.git'
hint: Updates were rejected because the remote contains work that you do not
hint: have locally. This is usually caused by another repository pushing to
hint: the same ref. If you want to integrate the remote changes, use
hint: 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

In [75]:
!git push --help